### ISSUE TITLE
Where can I download the file 

### ISSUE THREAD

**Issue by junxiesky** [organization/RapidPM#6]
As the title

**Comment by JellyBrick** [comment]
For _**Linux / macOS**_, After `git clone`, run the `install` script in the `ext` folder.
For _**Windows**_, run `phpize` and `configure.bat`, `nmake`

Attention: Still in development. **It does not work.**

**Comment by JellyBrick** [comment]
[Build status](https://travis-ci.org/organization/RapidPM)
[![Build Status](https://travis-ci.org/organization/RapidPM.svg?branch=master)](https://travis-ci.org/organization/RapidPM)

**Comment by junxiesky** [comment]
okay。

**Comment by benda95280** [comment]
Any compiled version ?

**Comment by JellyBrick** [comment]
@benda95280 Binary file will not be released until all features working.
